// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI3z97N0lI1A2KVRqDYHC3YwLawyMee4I',
    appId: '1:22853096622:web:20ac8c38754f30e13a893f',
    messagingSenderId: '22853096622',
    projectId: 'quanlyphongtro-fbd92',
    authDomain: 'quanlyphongtro-fbd92.firebaseapp.com',
    storageBucket: 'quanlyphongtro-fbd92.firebasestorage.app',
    measurementId: 'G-51YP1JJKBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAevKqcYsezO-TJ46XueP8VNxWXnyDpQ',
    appId: '1:22853096622:android:7c3d0888c75aa2713a893f',
    messagingSenderId: '22853096622',
    projectId: 'quanlyphongtro-fbd92',
    storageBucket: 'quanlyphongtro-fbd92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6LHMr0TDiVNmdpLv8kxkFE0xstUWrLI',
    appId: '1:22853096622:ios:f1cef7123857d8c53a893f',
    messagingSenderId: '22853096622',
    projectId: 'quanlyphongtro-fbd92',
    storageBucket: 'quanlyphongtro-fbd92.firebasestorage.app',
    iosBundleId: 'com.example.quanLyPhongTro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6LHMr0TDiVNmdpLv8kxkFE0xstUWrLI',
    appId: '1:22853096622:ios:f1cef7123857d8c53a893f',
    messagingSenderId: '22853096622',
    projectId: 'quanlyphongtro-fbd92',
    storageBucket: 'quanlyphongtro-fbd92.firebasestorage.app',
    iosBundleId: 'com.example.quanLyPhongTro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI3z97N0lI1A2KVRqDYHC3YwLawyMee4I',
    appId: '1:22853096622:web:c4f9ccd0ccc9be0d3a893f',
    messagingSenderId: '22853096622',
    projectId: 'quanlyphongtro-fbd92',
    authDomain: 'quanlyphongtro-fbd92.firebaseapp.com',
    storageBucket: 'quanlyphongtro-fbd92.firebasestorage.app',
    measurementId: 'G-WNLKHJC3M9',
  );

}